# Generated by Django 3.0.7 on 2020-06-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200619_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ptPhone',
            field=models.CharField(default='0905606857', max_length=100),
            preserve_default=False,
        ),
    ]
