# Generated by Django 3.0.7 on 2020-06-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_patient_ptphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Name',
            field=models.CharField(default='Khoa', max_length=100),
            preserve_default=False,
        ),
    ]
